version: '3'
services:
  java-app:
    container_name: 'tg-bot'
    image: $DOCKER_HUB_USERNAME/tg-bot:latest
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=$DATABASE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DATABASE_PASSWORD
      - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
      - TELEGRAM_BOT_NAME=$TELEGRAM_BOT_NAME
    restart: always
  postgres:
    image: postgres:15
    container_name: 'postgresql-db'
    ports:
      - 5432:5432 # DB available on 5432 port
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USERNAME
    restart: always