name: Build on PROD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      # Шаг 3: Разрешение на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Шаг 4: Сборка с Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Шаг 5: Тестирование с Gradle
      - name: Test with Gradle
        run: ./gradlew test

      # Шаг 6: Хранение артефактов сборки
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*.jar

      # Шаг 7: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Шаг 8: Построение Docker image
      - name: Build Docker image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_HUB_USERNAME }}/tg-bot:latest .   

      # Шаг 9: Push Docker image в Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/tg-bot:latest
